services:
  app:
    build: .
    ports:
      - "${PORT:-5000}:5000"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads

    # depends_on:
    #   - nats

  # nats:
  #   image: nats:latest
  #   ports:
  #     - "4222:4222"
